const CITIES=["Delhi","London","New York","Tokyo","Cairo","Sydney"];
const dashboard=document.getElementById("dashboard"),status=document.getElementById("status"),refresh=document.getElementById("refresh");
const state=new Map();
async function getJson(url){const r=await fetch(url);if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
async function geocode(city){const d=await getJson(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(city)}&count=1&language=en&format=json`);const x=d.results?.[0];if(!x)throw new Error(`City not found: ${city}`);return x}
async function loadCity(city){const g=await geocode(city);const f=await getJson(`https://api.open-meteo.com/v1/forecast?latitude=${g.latitude}&longitude=${g.longitude}&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max&forecast_days=6&timezone=auto`);state.set(city,{g,f});}
function localClock(tz){return new Intl.DateTimeFormat(undefined,{timeZone:tz,hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).format(new Date())}
function render(){dashboard.innerHTML="";for(const city of CITIES){const s=state.get(city);if(!s)continue;const d=s.f.daily;const card=document.createElement("article");card.className="card";card.dataset.tz=s.g.timezone;card.innerHTML=`<div class="city"><div><h2>${s.g.name}</h2><div class="country">${s.g.country||""}</div></div><div class="clock"><div class="time">${localClock(s.g.timezone)}</div><div class="tz">${s.g.timezone}</div></div></div><div class="forecast">${d.time.slice(0,6).map((date,i)=>`<div class="day"><div class="date">${new Date(date+"T12:00:00").toLocaleDateString(undefined,{weekday:"short",day:"numeric"})}</div><div class="temp">${Math.round(d.temperature_2m_min[i])}° / ${Math.round(d.temperature_2m_max[i])}°</div><div class="rain">${d.precipitation_probability_max[i]??"—"}% rain</div></div>`).join("")}</div>`;dashboard.appendChild(card)}}
function tick(){document.querySelectorAll(".card").forEach(c=>{const tz=c.dataset.tz;const el=c.querySelector(".time");if(el)el.textContent=localClock(tz)})}
async function load(){status.textContent="Loading six cities…";refresh.disabled=true;try{await Promise.all(CITIES.map(loadCity));render();status.textContent=`Updated ${new Date().toLocaleTimeString()} · 6 cities · 6-day forecast`}catch(e){status.textContent=`Unable to load weather: ${e.message}`}finally{refresh.disabled=false}}
refresh.addEventListener("click",load);load();setInterval(tick,1000);setInterval(load,15*60*1000);
